### ISSUE TITLE
Set timeout value in retrieve() function

### ISSUE THREAD

**Issue by LaurensJN** [osmlab/osmdiff#14]
Hey, awesome project! 

I have one problem: I'm using the osmdiff in my project and in about 5% of the cases the AugmentedDiff.retrieve() times out. Currently this is hardcoded on 30sec. Is there a possibility to have a option to set the timeout yourself as argument for the retrieve function?

**Comment by mvexel** [comment]
Closed with #15

**Comment by LaurensJN** [comment]
Thank you!
