### ISSUE TITLE
Getting Issue...Can somebody please help me

### ISSUE THREAD

**Issue by DaminiBansal** [osmlab/osmdiff#3]
pip install osmdiff
Collecting osmdiff
  Using cached osmdiff-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ToGO0q/osmdiff/setup.py", line 7, in <module>
        long_description = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ToGO0q/osmdiff/

**Comment by mvexel** [comment]
I uploaded a patch as 0.1.4 to PyPy, please try again and reopen if you still have problems.
