### ISSUE TITLE
incorrect installation pip install

### ISSUE THREAD

**Issue by Jagrmi-C** [osmlab/osmdiff#4]
module = self._system_import(name, *args, **kwargs)

ModuleNotFoundError: No module named 'osmdiff.osm'

**Comment by mvexel** [comment]
Uploaded 0.1.6 to PyPI, which fixes this.

**Comment by Jagrmi-C** [comment]
the same error
"from osmdiff import OSMChange"
the package is not fully installed.

The folder osm absent in osmdiff .

**Comment by mvexel** [comment]
Sorry, I don't understand what issue you are having, and I cannot reproduce is based on what information you give. Please feel free to re-open with full steps to reproduce.

When re-installing, make sure pip does not use an old cached version.

**Comment by Jagrmi-C** [comment]
pip install osmdiff==0.1.6
I install osmdiff just installed Ubuntu.
If I manually copy the folder <osm> in <somdiff> - everything is working
[image: Встроенное изображение 2]

[image: Встроенное изображение 1]

С уважением,
Романчик Андрей.
Мобильный телефон:

   - +375298888132

Skype:  jagrmi
Почта: a.ramanchyk@gmail.com

2017-12-06 3:03 GMT+03:00 Martijn van Exel <notifications@github.com>:
